### ISSUE TITLE
Don't distribute tarballs with dangerous instructions

### ISSUE THREAD

**Issue by strikerttd** [GoogleCloudPlatform/gcsfuse#119]
Following instructions for "Other Distributions" on a Fedora 22 machine seems to break the /sbin to /usr/sbin symlink and also changes the mode of /usr/sbin.  This causes Fedora to malfunction.

**Comment by jacobsa** [comment]
Yikes! Very sorry about that. I'll remove those instructions immediately, and try to find a better way to deal with this. Do you have any suggestions?

By the way, downloading and installing the `.rpm` file might work fine on Fedora. If you try it, can you let me know?

**Comment by jacobsa** [comment]
Reading about this a bit, it seems like it's probably enough to just ship a `.rpm` and a `.deb` file, and leave it up to the users of less common distributions to deal with those, since together they are nearly universal. (I am no expert in Linux software distribution, so please chime in if I'm wrong.)

So:

* Remove tarball packaging from `package_gcsfuse` for Linux (and for OS X once the homebrew formula is in).
* Update the installation instructions for other distributions to have sections for rpm and deb. Remove mentions of extracting tarballs.

**Comment by flowlo** [comment]
RHEL 7 RPM works for me on Fedora 22.

**Comment by strikerttd** [comment]
The RHEL 7 RPM on F22 does not seem to break anything.  Thanks, flowlo.
