### ISSUE TITLE
gcsfuse doesn't install on CentOS/RHEL

### ISSUE THREAD

**Issue by ahjohn** [GoogleCloudPlatform/gcsfuse#127]
Getting error (daemon dependency error) installing gcsfuse on CentOS 7.1 & RHEL 7.1

RHEL 7.1 error:
sudo yum install gcsfuse
Resolving Dependencies
--> Running transaction check
---> Package gcsfuse.x86_64 0:0.11.1-1 will be installed
--> Processing Dependency: fuse for package: gcsfuse-0.11.1-1.x86_64
--> Processing Dependency: daemon for package: gcsfuse-0.11.1-1.x86_64
--> Running transaction check
---> Package fuse.x86_64 0:2.9.2-5.el7 will be installed
---> Package gcsfuse.x86_64 0:0.11.1-1 will be installed
--> Processing Dependency: daemon for package: gcsfuse-0.11.1-1.x86_64
--> Finished Dependency Resolution
Error: Package: gcsfuse-0.11.1-1.x86_64 (gcsfuse)
Requires: daemon
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

Can anyone help? Thanks.

**Comment by jacobsa** [comment]
This is due to an [update](https://github.com/GoogleCloudPlatform/gcsfuse/commit/4dd253085a347161349903283b2fd6bcfb711bf3) I made to the installation instructions that should have waited for a release first. Please try again with [these instructions](https://github.com/GoogleCloudPlatform/gcsfuse/blob/7345f3085d0dd26e4b261093f07d4b88959704c6/docs/installing.md#centos-and-red-hat) and let me know if it works for you. Sorry about that!

**Comment by jacobsa** [comment]
The installation instructions should be correct (i.e. include the daemon install step) on the master branch now.

TODO: Revert 9b437e9047cbf9e96da998a51bdcb4b8fb929aa0 after making the next release.
