### ISSUE TITLE
Poor performance when using gcs/gcsfuse as a backup target

### ISSUE THREAD

**Issue by trg237** [GoogleCloudPlatform/gcsfuse#128]
I use veeam and am trying to use a google storage bucket as a backup destination. After setting it all up in google cloud platform, It works fine for about a minute, then throughput drops to zero for a few minutes, then works fine for about 10 seconds, then the throughput drops to zero, and so on.  It does read more from google storage cloud than I would expect, as it should all be write operations.

When backing up to a local disk on the same linux vm (on google compute) , it works as expected (full throughput and zero read operations from disk).

**Comment by kahing** [comment]
Was it an incremental or full backup? It's been a while since I've had to deal with veeam, but I remember there were specific settings that one need to enable for it to do bulk sequential writes.

**Comment by trg237** [comment]
It is a backup copy job with no initial data in the gcs bucket.  When writing to an attached disk in the google cloud instance, the same job showed 0 read operations in the google console.  I have the same setup in the amazon cloud using their storage gateway to an s3 bucket with no issue at all.

**Comment by kahing** [comment]
I am not very familiar with google cloud, but amazon storage gateway exposes an iscsi mountpoint and is very different from what gcsfuse is trying to do.

**Comment by trg237** [comment]
I am trying to move away from the iscsi mountpoint, as it adds a layer of complexity I do not need in the system. GCS fuse seems to fit what I am trying to accomplish, and I am not sure the reason behind the issues I am seeing.

**Comment by kahing** [comment]
Running gcsfuse with --debug_fuse and/or --debug_gcs may provide you with some insights into what veeam is doing. http://helpcenter.veeam.com/backup/70/bp_vsphere/sizing_repo_io_impact.html is also helpful in avoiding configurations that require random IOPS. Sorry it's been years since I've dealt with veeam and can't give you more detailed configurations.

**Comment by trg237** [comment]
Thanks for the help, I'll run with the debug operations and see if that gives any insight to what is going on in the background.

**Comment by jacobsa** [comment]
It sounds from the link above like at the very minimum you want to ensure you're using forward incremental backups with the active full mode, since that's the only configuration that's not heavy on random I/O. (There is also a more fundamental issue: please be sure that the file system makes all of the guarantees that veeam assumes. I have no idea how veeam works, so I couldn't tell you whether it does or not.)

I'm not sure there's anything for me to do here, so I'm closing this for now. If you dig in more deeply and find a performance problem that you can characterize in terms of veeam's load pattern on gcsfuse, please do update the thread. Thanks!
