### ISSUE TITLE
proftpd upload fails when uploading big file.

### ISSUE THREAD

**Issue by xastor** [GoogleCloudPlatform/gcsfuse#136]
I have a proftpd daemon running on top of a gcsfuse filesystem. 
When I try to upload a big file (37Gb) the server starts experiencing very high cpu load after the first few Gb are uploaded.  The transfer eventually times out.  I think it times out due to the high cpu load.

When reading documentation, my first guess is that proftpd ends up doing random writes.  Could this be the case or is this unlikely?  Any insight would be appreciated...

For reference : I'm using a f1-micro compute engine.

**Comment by jacobsa** [comment]
Hi, sorry I don't know anything about how proftpd works. Can you try running with `--debug_fuse` and/or `--debug_gcs` to get some insight into what operations are being performed and how long they are taking?

**Comment by xastor** [comment]
I just restarted the transfer with logging enabled.  This block is recurring all the time : 

```
fuse_debug: Op 0x000000d1        connection.go:395] <- WriteFile (inode 3, handle 0, offset 17178624, 131072 bytes)
fuse_debug: Op 0x000000d2        connection.go:395] <- WriteFile (inode 3, handle 0, offset 17309696, 131072 bytes)
fuse_debug: Op 0x000000d3        connection.go:395] <- WriteFile (inode 3, handle 0, offset 17440768, 131072 bytes)
fuse_debug: Op 0x000000d4        connection.go:395] <- WriteFile (inode 3, handle 0, offset 17571840, 131072 bytes)
fuse_debug: Op 0x000000d5        connection.go:395] <- WriteFile (inode 3, handle 0, offset 17702912, 29100 bytes)
fuse_debug: Op 0x000000d6        connection.go:395] <- SetInodeAttributes (inode 3, mtime 2015-10-26 08:58:04.055888931 +0000 UTC)
fuse_debug: Op 0x000000d6        connection.go:474] -> OK
fuse_debug: Op 0x000000d1        connection.go:474] -> OK
fuse_debug: Op 0x000000d2        connection.go:474] -> OK
fuse_debug: Op 0x000000d3        connection.go:474] -> OK
fuse_debug: Op 0x000000d4        connection.go:474] -> OK
fuse_debug: Op 0x000000d5        connection.go:474] -> OK
```

Does this reveal random writes happening?

**Comment by jacobsa** [comment]
No, those are consecutive—each offset + 131072 is equal to the next offset. Even if they were random, that's fine for a _new_ file. Anything interesting with `--debug_gcs`? My guess is no, since nothing should show up until the entire file has been staged and is ready to upload.

Alternatively, are you able to give me step by step instructions to reproduce this, say on a Google Compute Engine VM? Or even better, set it up for me and give me login access?

**Comment by xastor** [comment]
The transfer timed out again. Every minute I see this message : 

```
gcs: Req              0xd: <- StatObject("guest/raster_vlaanderen.zip")
gcs: Req              0xd: -> StatObject("guest/raster_vlaanderen.zip") (245.729653ms): OK
```

The transfer seems to end here.  Does this give anything away?

```
fuse_debug: Op 0x000030f1        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1178681344, 131072 bytes)
fuse_debug: Op 0x000030f2        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1178812416, 131072 bytes)
fuse_debug: Op 0x000030f3        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1178943488, 131072 bytes)
fuse_debug: Op 0x000030f4        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1179074560, 131072 bytes)
fuse_debug: Op 0x000030f5        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1179205632, 32768 bytes)
fuse_debug: Op 0x000030f6        connection.go:395] <- SetInodeAttributes (inode 3, mtime 2015-10-26 09:38:51.559266263 +0000 UTC)
fuse_debug: Op 0x000030f6        connection.go:474] -> OK
fuse_debug: Op 0x000030f1        connection.go:474] -> OK
fuse_debug: Op 0x000030f2        connection.go:474] -> OK
fuse_debug: Op 0x000030f3        connection.go:474] -> OK
fuse_debug: Op 0x000030f4        connection.go:474] -> OK
fuse_debug: Op 0x000030f5        connection.go:474] -> OK
fuse_debug: Op 0x000030f7        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1179238400, 46574 bytes)
fuse_debug: Op 0x000030f8        connection.go:395] <- SetInodeAttributes (inode 3, mtime 2015-10-26 09:38:52.239266002 +0000 UTC)
fuse_debug: Op 0x000030f8        connection.go:474] -> OK
fuse_debug: Op 0x000030f7        connection.go:474] -> OK
fuse_debug: Op 0x000030f9        connection.go:395] <- WriteFile (inode 3, handle 0, offset 1179283456, 14298 bytes)
fuse_debug: Op 0x000030fa        connection.go:395] <- SetInodeAttributes (inode 3, mtime 2015-10-26 09:39:11.763261832 +0000 UTC)
fuse_debug: Op 0x000030fa        connection.go:474] -> OK
fuse_debug: Op 0x000030f9        connection.go:474] -> OK
fuse_debug: Op 0x000030fb        connection.go:395] <- FlushFile (inode 3)
gcs: Req             0x3a: <- CreateObject("guest/raster_vlaanderen.zip")
```

After this I see 

The server's not my property, but I can describe how to reproduce later.

**Comment by jacobsa** [comment]
`FlushFile` is the point at which gcsfuse will start to write an object to GCS, and indeed it sends a `CreateObject` request. You said it times out, but how long did you wait for it? It looks like you're trying to write >1.1 GiB.

**Comment by xastor** [comment]
Mystery solved : the ftp client had a transfer timeout of 20 seconds..  I suppose that write was not yet done when the client decided to disconnect.  Thanks for your expertise and swift responses! :-)

**Comment by jacobsa** [comment]
Cool, glad you figured it out.

**Comment by coreylang** [comment]
Hi, I to have ProFTPd running on top of the gcsfuse filesystem. I can upload file objects when connected to the ftp server, but when it attempts to create a directory it returns "550 Function not implemented". When using -foreground with debug flags on, it says Function not implemented. It seems to not allow the FTP client to send MKD or MKDIR commands. Would this be correct?

**Comment by jacobsa** [comment]
Could you please post the log from `--foreground` `--debug_fuse` as a [gist](https://gist.github.com/)?

**Comment by coreylang** [comment]
secret gist: https://gist.github.com/coreylang/ce7c5ccadd00c11fe3c21f32cbc7db07

when mounting the bucket to a path on the local drive (centos) I am using (paths and bucket names are substituted but the mount path is under /mnt):
gcsfuse -o allow_other --foreground --debug_gcs --debug_fuse -file-mode=660 -dir-mode=770 --uid=48 --gid=48 gc-bucket-name /mnt/gc-bucket-mnt

I am using ProFTPd to upload files and the debug data in the gist appears. I tried creating a "directory" named "test". Note, using the same ProFTPd connection with a different ftp user and different directory works as expected when trying to create a "directory" named "test".

**Comment by jacobsa** [comment]
It looks like the "not implemented" error is happening because proftpd is making a `rename` syscall, but this [isn't supported](https://github.com/googlecloudplatform/gcsfuse/blob/941ac7e9afb3ef89a51100e10b418e1f90c22388/docs/semantics.md#missing-features). Are you able to use `strace` to figure out what it's renaming? Do you have any idea why it would do that?

I'm a bit confused by your second to last paragraph. Are you saying that for some FTP connections it works, and for some it doesn't?

**Comment by coreylang** [comment]
I meant when I make connections to the same server but not in the GCS fuse file system I am able to create directories successfully.

It appears when ProFTPd attempts to create a directory it creates a directory with a random temporary name. The following is from the debug verbose output in the gist in above:

fuse_debug: Op 0x00000074        connection.go:476] -> Error: "no such file or directory"
fuse_debug: Op 0x00000075        connection.go:395] <- MkDir (parent 4, name ".dstXXX2sNtfP")
gcs: Req             0x1a: <- CreateObject("1000000001_Container/app-num-1_Project/Deployment_Source/.dstXXX2sNtfP/")
gcs: Req             0x1a: -> CreateObject("1000000001_Container/app-num-1_Project/Deployment_Source/.dstXXX2sNtfP/") (314.116678ms): OK


It successfully created the temporary directory ./dstXXX2sNtfP. Then it attempts to rename the directory after the server confirms the attended name for the directory does not already exist:

fuse_debug: Op 0x0000007c        connection.go:395] <- LookUpInode (parent 4, name "test")
fuse_debug: Op 0x0000007c        connection.go:476] -> Error: "no such file or directory"

Because the "Rename" functionality/command is not supported it has to delete the temporary hidden directory it created:


fuse_debug: Op 0x0000007d        connection.go:395] <- Rename
fuse_debug: Op 0x0000007d        connection.go:476] -> Error: "function not implemented"
fuse: 2017/01/09 21:19:07.483738 *fuseops.RenameOp error: function not implemented
fuse_debug: Op 0x0000007e        connection.go:395] <- LookUpInode (parent 4, name ".dstXXX2sNtfP")
fuse_debug: Op 0x0000007e        connection.go:474] -> OK (inode 15)
fuse_debug: Op 0x0000007f        connection.go:395] <- RmDir (parent 4, name ".dstXXX2sNtfP")


I don't know if this would be a common practice of ALL FTP daemons, but this appears to be what ProFTPd is doing in the version I am running. "ProFTPD Version 1.3.5b".


Have you been able to successfully create directories with other ftp daemons on top of your GCS fuse filesystem? Any advice on what I should do? I am thinking about how to change versions of ProFTPd or daemons all together.

Thanks

**Comment by jacobsa** [comment]
Unfortunately renaming directories is simply unsupported (and can't be supported). Sorry. I've never used an FTP daemon with gcsfuse, no.

**Comment by xastor** [comment]
I also ran into the same rename issue and stopped trying to run proftpd on top of gcs shortly afterwards.  When you think about it, an ftp server where you can't move or rename files makes little sense.
