### ISSUE TITLE
Mounting is hanging forever

### ISSUE THREAD

**Issue by gabipetrovay** [GoogleCloudPlatform/gcsfuse#139]
When I mount a bucket with `gcsfuse` (regardless is using the `root` account or a normal user) the mounting process freezes after a while:

```
root@4d973c9b5fbf:/app# gcsfuse test_bucket_gabi /app
Opening GCS connection...

WARNING: gcsfuse invoked as root. This will cause all files to be owned by
root. If this is not what you intended, invoke gcsfuse as the user that will
be interacting with the file system.

Opening bucket...
Mounting file system...
File system has been successfully mounted.
2015/11/19 15:05:41.234632 Received SIGINT, attempting to unmount...
2015/11/19 15:05:41.236013 Successfully exiting.
```

I pressed Ctrl-C, then:

```
root@4d973c9b5fbf:/app# ls -l /app/
total 0
root@4d973c9b5fbf:/app# su service /bin/bash -c "gcsfuse test_bucket_gabi /app"
Opening GCS connection...
Opening bucket...
Mounting file system...
File system has been successfully mounted.
```

While this is running I can see from another terminal that nothing has been mounted yet.

I am running a Debian in a Docker container that I run with `docker run --rm -ti --privileged myImage` (Without `--privileged` I get: `fusermount: failed to open /dev/fuse: Operation not permitted`)

**Comment by Gibbsdavidl** [comment]
I'm having the same issue. While running in a docker container ... I get the message that the file system has been successfully mounted. Then it hangs ... until I hit ctrl-c and it successfully exits.

**Comment by jacobsa** [comment]
(Sorry for the slow response; vacation.)

`gcsfuse` isn't hanging; the file system has been successfully mounted and it stays in the foreground until it is unmounted. See [here](https://github.com/googlecloudplatform/gcsfuse#invoking-gcsfuse) and [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#mounting). And [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#running-as-a-daemon) if you want to do otherwise.

If you find that this is not the case, I suspect it has something to do with your Docker setup; perhaps you're mounting inside the container and running `ls` outside, or vice versa?

**Comment by Gibbsdavidl** [comment]
Sorry!  I read the docs(!), and running it with daemon did it.  Just wasn't the behavior I expected I guess.  :) Thank you! Go back to your vacation!

**Comment by jacobsa** [comment]
No worries, done with vacation now. Glad it's working. :-)
