### ISSUE TITLE
GCSFuse sidecar is not compatible with restricted Kubernetes pod security standard

### ISSUE THREAD

**Issue by siarhei-cma** [GoogleCloudPlatform/gcsfuse#1446]
**Describe the issue**
We successfully mounted Cloud Bucket as described here: [https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver)
The sidecar starts it has following security context:

```      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: true
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
```

Accordingly to the Kubernetes "restricted" standard: 
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
the capabilities value should be:

```        capabilities:
                 drop:
                  - ALL
```

It appears that the case mattes (all vs ALL) since when we run: 

`kubectl label --dry-run=server --overwrite ns --all pod-security.kubernetes.io/enforce=restricted`

we get the message:

_Warning: existing pods in namespace "namespace" violate the new PodSecurity enforce level "restricted:latest"
Warning: podname: unrestricted capabilities_

where "namespace" and "podname" are the namespace and the pod with  GCSFuse sidecar. If we remove the GCSFuse sidecar the messages above goes away.

**System (please complete the following information):**
 - Platform: GKE Kubernetes cluster v 1.26.7-gke.500

**Comment by siarhei-cma** [comment]
This is similar to this issue:
https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/52

**Comment by ashmeenkaur** [comment]
Hi @siarhei-cma,

Thank you for bringing this issue to our attention. The fix is included in the latest release and the GCSFuse CSI driver team is waiting for the rollout to complete. It is expected to be completed by the end of this week.

In the meantime, you can use the workaround mentioned in https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/52.

I am closing this issue as a duplicate of https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/52. Please track the linked bug for updates.

Feel free to reopen this issue if you have any other questions.

Thanks,
Ashmeen
