### ISSUE TITLE
store Unix user:group & file permission bits

### ISSUE THREAD

**Issue by lordtangent** [GoogleCloudPlatform/gcsfuse#149]
Feature request: Support storing the UID, GID and basic Unix file permissions as x-goog-meta custom metadata. (rwx ,  setuid, setgid and sticky)  We'd like to create an elastic NAS using GCS as our backing storage. However, we need to be able to store traditional Unix file permissions at the minimum for it to work.

**Comment by jacobsa** [comment]
gcsfuse intentionally does the simple thing here, because it's not at all clear what these things should mean across machines (and because there is no clear mapping onto GCS's ACL model, which is what we would otherwise use). Sorry, if you need this for your application you may be better off writing directly to the GCS API.
