### ISSUE TITLE
debug-gcs logs location ?

### ISSUE THREAD

**Issue by suhas22** [GoogleCloudPlatform/gcsfuse#156]
Hi Aaron,
is there any way to configure a location where gcs fuse writes the debug logs to, or is there a predefined location where --debug-gcs logs is written to ?

Currently i am doing it this way round : 
nohup gcsfuse --debug-gcs --foreground --temp-dir /data bucketname foldername > /var/log/gcsfuse.txt &

I feel there is one bug here, beacuse if i just use nohup gcsfuse --temp-dir /data bucketname foldername > /var/log/gcsfuse.txt & nothing gets written, meaning debug_gcs output does not print unless we give the --foreground option.

I mean unless we give the --foreground option, it just says bucket successfully mounted, exits and comes back to the terminal.

**Comment by jacobsa** [comment]
The debug output is written to stderr. If you don't set `--foreground`, stderr points at `/dev/null`, so that's required.

I've never used `nohup`, so I can't say whether you've done this right or not. You'll need to look into what it does with stderr. [This answer](http://unix.stackexchange.com/a/45915/118501) may be helpful.
