### ISSUE TITLE
Support GCS Object Change Notification API

### ISSUE THREAD

**Issue by dalbani** [GoogleCloudPlatform/gcsfuse#166]
As mentioned on http://serverfault.com/questions/722589/does-gcsfuse-use-a-vfs, `gcsfuse` doesn't make use of GCS [Object Change Notification API](https://cloud.google.com/storage/docs/object-change-notification).

Do you think it would have sense to do so? The main use case I have in mind is mounting the same bucket on several `gcsfuse` instances (e.g. 1 writer, several readers), without resorting to continuous polling to keep all instances always in sync.
In practice, I'm kind of worried about the implementation aspect, given that Object Change Notifications are actually HTTPS callbacks to a pre-authorized web host.
How would that fit within `gcsfuse` architecture? Would that require some workaround based on a [PageKite](http://pagekite.net)-like (reverse proxy) service?

As a hands-on exercice to learn the Go language, I am contemplating the idea of having a try. But given the technical constraints mentioned above, is it doomed to fail? :-)

**Comment by jacobsa** [comment]
Yeah, this is difficult because of all the management of callbacks required. But I'm also not sure I understand your use case—if you disable caching or set your cache settings appropriately, your readers will automatically be in sync with your writer.

**Comment by dalbani** [comment]
Err, then I suppose I'm confusing with the VFS feature mentioned in the serverfault thread I linked to.
My goal is to have reader `gcsfuse` instances be automatically up to date with modifications in the bucket without having to do any polling. Disabling the cache doesn't provide this capability, does it?

**Comment by jacobsa** [comment]
Reader gcsfuse file systems will be automatically up to date in the sense that if you go to open a file you'll see the new version, but you won't get any sort of "push" notifications via inotify etc.

**Comment by dalbani** [comment]
Yes, that's precisely that "push" functionality that I had in mind.

-- 
Damiano Albani

**Comment by jacobsa** [comment]
I see, sorry. Yeah, that is difficult and unlikely to happen, to be honest. You could of course have your application use GCS's notifications directly.

**Comment by sshcherbakov** [comment]
inotify notifications on changes in GCS mount are a useful use case, for example to allow applications to pickup changes from the file system automatically on the GCS bucket contents change (e.g. automatic Google CAS TLS trust bundle reload).

At the moment when the change in the gcsfuse mounted directory is introduced in the VM/machine, then the inotify sees the events and an application can react. When the file is added to the bucket via Google API, the inotify doesn't get notified about that change even though an `ls` in the mounted folder reveals the change.

As I understand the outcome of the discussion in this ticket, the alternative is to subscribe to the GCS Pub/Sub notifications instead of the local file system events.
