### ISSUE TITLE
gcsfuse randomly stopped working twice

### ISSUE THREAD

**Issue by aachik** [GoogleCloudPlatform/gcsfuse#167]
Hello, i'm using gcsfuse inside a gce instance to save videos of a webcam and the users screen into a folder which is connected(?) to a bucket and then play them back together into a web player.

a program has to write everything inside the gce instance is installed and works as a service which has permissions to write, read, etc... the problem is that at some point gcsfuse stops working, inside the bucket i cant find any of the files anymore but i do can find them inside the gce instance filesystem, in order to be able to write in the folder i have to either unmount the folder using `umount bucket-name` then delete it and then mount it back again with the same instructions.

more information:
`Ubuntu 14.03 lts`

folder where is mounted
`/home/user/storage`

instruction used(/home/user/):
`gcsfuse bucket-name storage`

if i try to mount the folder into the bucket again after it crashed, it says:

```
user@machine:~$ gcsfuse bucket-name storage
Using mount point: /home/user/storage
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: fusermount: exit status 1
```

so i have to:
1. umount bucket-name
2. delete the folder storage
3. create the folder storage again
4. gcsfuse bucket-name storage
5.- my project works again like nothing happened(most of the time)

question[important]: does gcsfuse has a log folder or a way to monitor its health or something?

question2: because it works most of the time i just wanna know if maybe i did something wrong with the instruction i used, should i do something else besides using that instruction(gcsfuse bucket-name storage)?

thanks

**Comment by jacobsa** [comment]
Hi, a few things:

1. Please update to gcsfuse 0.17.1, which gives at least slightly better error output when `fusermount` fails.

2. This is probably caused by you attempting to mount when the folder is already mounted, perhaps because gcsfuse didn't exit cleanly or because you unmounted incorrectly.

3. To correctly unmount, use `fusermount -u`. See docs [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/mounting.md#unmounting).

4. If you want to monitor gcsfuse, set the `--foreground` option to stay in the foreground and then use your favorite tool for monitoring the health of a process, scraping its stderr for logs, etc.

5. If you continue to experience issues, make sure to run in the foreground and look at stderr. Try `--debug_gcs` and `--debug_fuse` for more helpful output.

Does this help?
