### ISSUE TITLE
Mount path passed as bucket name in linux

### ISSUE THREAD

**Issue by jasper1918** [GoogleCloudPlatform/gcsfuse#169]
Same as #129 

This is still giving issues on version 0.17.1. using ubuntu 14.04.

**Comment by jacobsa** [comment]
See [this comment](https://github.com/GoogleCloudPlatform/gcsfuse/issues/129#issuecomment-142135225). As far as I can tell, the issue is because the `mount` command on your system has the unfortunate "feature" of trying to helpfully turn arguments that happen to match a relative directory name into absolute paths before calling through to gcsfuse.

There's nothing I can do about this; you'll need to work around it by running gcsfuse in a directory where there is no sub-directory whose name matches the bucket name.
