### ISSUE TITLE
Concurrent Map iteration and map write

### ISSUE THREAD

**Issue by rpemsel** [GoogleCloudPlatform/gcsfuse#1726]
**Describe the issue**
A user of our platform that uses GCS FUSE via GCS FUSE CSI Driver reported an issue with the GCS Fuse part of the implementation. The sidecar container running GCS Fuse broke down with an error message of "Concurrent Map iteration and map write". Also see the following logs 
[downloaded-logs-20240219-062431.json](https://github.com/GoogleCloudPlatform/gcsfuse/files/14326881/downloaded-logs-20240219-062431.json). 

According to the logs it looks a bit like an issue with finding a census for concurrent read/write processes. Unfortunately this issue cannot easily be reproduced. 

**System (please complete the following information):**
 - OS: COS
 - Platform Kubernetes via GCS FUSE CSI Driver
 - Version: 0.1.12 (GCS Fuse CSI Driver)

**Additional context**
The issue occurred during high load read/write operations

**SLO:**
We strive to respond to all bug reports within 24 business hours.

**Comment by ashmeenkaur** [comment]
Hi @rpemsel, 

Thanks for reporting this issue! The fix has been merged into master and will be included in the March 2024 release.

Thanks,
Ashmeen

**Comment by Tulsishah** [comment]
This issue was resolved in GCSFuse [v2.0.0](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v2.0.0). Please upgrade and reopen the issue if necessary.

Thanks,
Tulsi Shah

**Comment by tred77** [comment]
Thanks for the fix, 
Is there any page mapping with gcsfuse/driver is used in which GKE release channel version?
Could not find any documentation not in GKE side nor gcsfuse/Driver side

**Comment by sethiay** [comment]
@tred77 Please take a look at https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/releases.md#gke-compatibility

**Comment by tred77** [comment]
@sethiay I have one more question
Since in my case the new version is not available in the gke stable channel, I am not able to upgrade it. Meanwhile I was thinking to implement a health check using kubernetees livenessProbe and readinessProbe. I was wondering if there is better way to make sure that the mount is live than using ls command. Because, behind the scene ls command would be translated to list which is already part of the problem and I don't want to make my system more flaky by adding extra list operation.

**Comment by sethiay** [comment]
@tred77 Could you please bring this on https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/ repository ? Thanks !
