### ISSUE TITLE
Possible Memory Leak with gcsfuse version 0.18.0

### ISSUE THREAD

**Issue by githubwua** [GoogleCloudPlatform/gcsfuse#173]
$ gcsfuse --version
gcsfuse version 0.18.0 (Go version go1.6.2)

The gcsfuse process starts out small with a small RES memory footprint.  As files are being copied to a bucket, RES memory keeps on growing until it exhausts all of the RAM.  This appears to be a new issue, introduced by the May 23rd update. 

Here's a small script to reproduce the issue:

  while true; do cp /var/log/* /path/to/mount; sleep 5.0; done

The output of htop will show an increasing RES memory size.

**Comment by jacobsa** [comment]
I'm unable to reproduce this–the best I can do is get the heap size (as reported by `GODEBUG=gctrace=1`) to 5 MB, and the resident size (as reported by `ps auxww`) to about 26 MB.

A few things:

1. Which version exactly were you using before 0.18.0?
2. How much RAM are we talking about?
3. Can you give a more self-contained process to reproduce this? One that doesn't depend on the contents of `/var/log` would be good.
4. Can you run `GODEBUG=gctrace=1 gcsfuse --foreground ...` and give the debugging output from the garbage collector early and late in the program's lifetime?

**Comment by jacobsa** [comment]
Maybe also the output with `--debug_fuse` would be helpful, to make sure your kernel isn't doing something whacky and never forgetting inodes.

**Comment by githubwua** [comment]
I am unable to reproduce it with version 0.18.1.  Did we make any change to 0.18.0?

**Comment by jlmda** [comment]
I'm attempting to capture the log data now. Previously, we had been using `gcsfuse version 0.17.1 (Go version go1.6)`. It was `gcsfuse version 0.18.0 (Go version go1.6.2)` where we first began having this problem. I notice that the Go version also changed between gcsfuse versions.

**Comment by jlmda** [comment]
Here is a use case that causes a rapid increase in memory usage up until it hits the OOM killer:

`GODEBUG=gctrace=1 gcsfuse --foreground --debug_fuse -o allow_other --implicit-dirs earthengine-public /earthengine-public`
`md5sum /earthengine-public/landsat/L8/015/033/*`

Attached is an error log that was produced by the above. I removed all lines containing "connection.go:{474|395}" for brevity's sake.
[error.zip](https://github.com/GoogleCloudPlatform/gcsfuse/files/291560/error.zip)

**Comment by jacobsa** [comment]
Thanks. But:

1. Again your example isn't self-contained, so I'm not going to be able to reproduce. Can you either set up a public bucket where I can do this, or give me a hermetic repro case that doesn't depend on files that exist only on your bucket or system?

2. The lines from `connection.go` are exactly what I'm looking for. Are you able to leave them in?

**Comment by jacobsa** [comment]
(Oh sorry, I see that there are two people in this thread. :-) The above still applies though. @jlmda, please clarify what version you were running too.)

**Comment by jlmda** [comment]
Understood - here is the log file, unabridged. I'll see if I can create a totally independent case. The `earthengine-public` bucket is public, though - you should be able to mount that and see exactly the same behavior that I'm seeing. The version used in this test was 18.0, though I suspect that 18.1 has the same behavior.
[gcsfuse_earthengine-public.zip](https://github.com/GoogleCloudPlatform/gcsfuse/files/293424/gcsfuse_earthengine-public.zip)

**Comment by jacobsa** [comment]
Thanks, I'm embarrassed that I didn't realize that bucket would probably be public.

With your example I can reproduce high peak memory usage (~3 GB RSS), but after read traffic stops:

*  The Go garbage collector soon brings the heap back to a few hundred MB.
*  After another GC run (two minutes later) it goes down to 2 MB.
*  After 5-10 minutes the Go heap scavenger releases memory to the system, bringing RSS down to 111 MB. I suspect it would fall further if I waited for another scavenger run.

Heap profiling shows that the RAM is allocated by the receive loop for the HTTP connection (in particular, `http2clientConnReadLoop.processData` calls `http2pipe.Write` which calls `bytes.Buffer.Write`). The HTTP2 part in there is interesting. Here is the Go version information from the last few versions available from `yum`:

 *  `gcsfuse version 0.17.0 (Go version go1.6)`
 *  `gcsfuse version 0.17.1 (Go version go1.6)`
 *  `gcsfuse version 0.17.2 (Go version go1.6.2)`
 *  `gcsfuse version 0.18.0 (Go version go1.6.2)`
 
The behavior I described above is with 0.18.0. With 0.17.0 I get *much* less memory usage (heap never goes above 4 MB). Ditto 0.17.1. But 0.17.2 is where the usage shoots up. So it seems this may be due to Go 1.6.2.
 
Still to do:
 
 *  Try building gcsfuse 0.17.2 with Go 1.6 and Go 1.6.1. Confirm the memory usage is low.
 *  Try building gcsfuse 0.17.2 before and after golang/go@406752b640fcc56a9287b8454564cffe2f0021c1, confirming that the issue is caused by using HTTP2 support.
 *  Figure out if Go's HTTP2 receive buffer usage is sane. For what it's worth when I run with `--limit-bytes-per-sec=512000` to limit to 512 KB/s downstream, the memory usage is still high. But it's not (or at least takes a long time to grow?) when I set 1 KB/s.

**Comment by jacobsa** [comment]
It looks like the HTTP2 package does have a notion of fixed-size buffers which are used when [making a request](https://github.com/golang/go/blob/f6c0241999bffe0fe52e8b7f5bbcc8f9e02edbdf/src/net/http/h2_bundle.go#L4184), but when receiving a response [the buffer is unbounded](https://github.com/golang/go/blob/f6c0241999bffe0fe52e8b7f5bbcc8f9e02edbdf/src/net/http/h2_bundle.go#L6066-L6067). My results with `--limit-bytes-per-sec=1000` above show that the upstream networking code does see the pushback eventually, but I don't yet understand how.

**Comment by jacobsa** [comment]
Indeed when I invoke gcsfuse with `GODEBUG=http2client=0` in the environment (as documented [here](https://golang.org/pkg/net/http/#pkg-overview)), I can't reproduce this anymore.

@jlmda @githubwua Can you confirm the issue goes away when you do this?

**Comment by jacobsa** [comment]
Okay yeah, I reproduced this with a minimal program in golang/go#15930. I'm quite sure that this is an issue with Go's HTTP/2 library.

I'll make a gcsfuse point release that disables HTTP/2.

**Comment by jacobsa** [comment]
@jlmda @githubwua This should be fixed in gcsfuse 0.18.2. Please let me know whether the problem is gone for you.

**Comment by jlmda** [comment]
Excellent work @jacobsa, this appears to have fixed the problem. Thank you!
