### ISSUE TITLE
Performance Tuning options and  --temp-dir questions

### ISSUE THREAD

**Issue by capriguy84** [GoogleCloudPlatform/gcsfuse#201]
I would like to add weight to the existing open ticket #184 and at the same time see what other tuning parameters available to improve the seek time.

Mount Command:

`/usr/bin/gcsfuse --stat-cache-ttl "1h" --type-cache-ttl "1h" --limit-bytes-per-sec "-1" --limit-ops-per-sec "-1" --implicit-dirs --gid 10015 --temp-dir /tmpfs -o ro,allow_other my-bucket /fs/data-03
`
**Issues Noticed:**
-  Just like the #184 , I am seeing delays when trying to list files. I agree it is still work in progress.

**Questions:**
1. My data is mostly static, so I don;t care about new files, so setting cache values to 1hr. My question is can I force the cache operation on particular heirarchy? And can I see the cached data somewhere like --temp-dir? I have about 30k files stored.
2. How does the --temp-dir work? Does the fuse module cache the full file or only metadata? 
3. Currently, I am using the RAM disk for --temp-dir. What are the sizing considerations for this? 
4. All the files uploaded to GCS are .zip files. Will see any improvements, by modifying metadata? My object currently shows “application/zip” with below info. Can any of those be pruned to improve the fetch performance?
5. Lastly, is there any difference in adding new files between "gsutil -m rsync" & mount the GCS as RW and then perform RW? Or are they both the same?

```
gs://my-bucket/data/mydata/data/2016/12/02/DIR_T/PPP_20161202_QT.zip:
    Creation time:          Wed, 07 Dec 2016 19:31:58 GMT
    Update time:            Wed, 07 Dec 2016 22:53:41 GMT
    Storage class:          STANDARD
    Content-Length:         10577216874
    Content-Type:           application/zip
    Metadata:
        goog-reserved-file-mtime:1480821295
    Hash (crc32c):          bP/jTA==
    Hash (md5):             MHIv3wV+HQ7lHWk3SJghXQ==
    ETag:                   CIXQrZjp4tACEAI=
    Generation:             1481139118893061
    Metageneration:         2
    ACL:                    [:

```

**Comment by jacobsa** [comment]
Hi, can you clarify what your hierarchy looks like in terms of directory structure and number of direct and indirect descendants? Issue #184 is about directories that have few direct descendants, but many indirect.

1. I don't know what you mean by "force the cache operation on particular heirarchy". If you're talking about caching for listings, there currently is no caching. (That's issue #184.) As for seeing the contents of the cache: it's all in memory; there's nowhere to see it in the file system.

2. `--temp-dir` is used for storing the contents of files that you have dirtied by writing to them. It's unrelated to metadata.

3. You want to size `--temp-dir` so that it's large enough to contain all of the files that you have written to and not closed.

4. I'm not sure what kind of modifications you're speaking of here. `.zip` files aren't treated special in any way.

5. I'm unfamiliar with the implementation of `gsutil rsync`, but it sounds like the `-m` flag causes it to parallelize across files. If so, that's going to be significantly faster than using plain old `rsync`, which does one file at a time, a strategy that doesn't make sense for a high-latency file system.

**Comment by capriguy84** [comment]
Thanks for taking time to 

My hierarchy of dirs and files looks like this. "Dir{1..30}/YYYY/MM/DD/<100-files>"
The YYYY range is 1993 to 2016.

1.  I meant caching for listing and some sort of paging for files to speed up the seeks. Let's say I need only YYYY=1993-1995. I was hoping to see if there is way to prioritize that. I guess not.

2. Thanks for clarifying the usage of --temp-dir. My use case of gcsfuse is to mount GCS as read-only on instances. I guess then this flag doesn't apply to me as I am not writing.

3. I assumed there is some caching for listing using --temp-dir but guess I stand corrected now.

4. My intention was to learn if there is some optimization available to speed up by pruning metadata. I guess not.
[](https://cloud.google.com/compute/docs/storing-retrieving-metadata)

5. Pls ignore this question. 

Thanks Again!

**Comment by jacobsa** [comment]
1. Caching for listing is covered in #184. (I will consider this a vote, thanks.) I don't know what you mean by "paging for files" or by "seeks" in this context.

2. Please confirm for yourself, but yes I believe you should see no usage for that directory.
