### ISSUE TITLE
Is this viable for production environments?

### ISSUE THREAD

**Issue by danemacmillan** [GoogleCloudPlatform/gcsfuse#217]
I have a few questions. They've been numbered for easy reference.

I've been researching GCS buckets and how to mount them. This tool seems to be the official one. After mounting a bucket and testing it with file and directory creations, I immediately noticed the lag these operations have. My objective is to share a bucket among multiple load balanced instances. The bucket will primarily contain two things:

- Log files from all these instances. Each instance will write to the same log files. There are maybe a few logs per second per instance.
- Shared media. This shared media currently contains 140GB of images. Most of them are JPEG. New image originals, and thumbnails derived from them, are created throughout the day. There are many, many directories, and many, many files. Image originals will be getting read and resized into small thumbnails.

Based on my experience just echoing text into files and creating directories, (1) can I expect the above configuration to only exacerbate the lag, or will the above configuration be handled without concern? Not to mention, issue https://github.com/GoogleCloudPlatform/gcsfuse/issues/204 is a bit disconcerting; (2) can I expect intermittent disconnections while my customers are trying to access the site?

The README also states that when downloading objects they are temporarily stored on the filesystem. (3) Given that one bucket will be at least 140GB, does that mean, to be absolutely safe, that each instance should be at least as large? My instances are configured to run a single codebase, and do not need to be larger than 10GB each. Anything more will really drive the costs up.

I read https://cloud.google.com/compute/docs/disks/. It states that "[t]he Regional Storage class has performance that is comparable to persistent disks but with higher latency and less consistent throughput characteristics." I suppose that mostly answers the question about lag, but (1a) does that still apply when mounted, and will the amount of files and directories I mentioned be a problem, as well as the read and write operations that will be performed?

I also read that when mounted, each instance "can write data to a file and overwrite critical data from other instances that are also writing data to the storage object simultaneously." Just a few sentences prior, though, it states that "you can read and write data to a bucket from multiple instances simultaneously." That lead me to believe there's no concern about multiple instances accidentally overwriting each other's information. (3) Which is it?

I realize the README states this is beta status, but given the lack of alternatives, (4) is the goal of this tool to eventually become the best way of sharing data among instances, or are there alternatives yet unknown that will be announced?

(5) Is this viable for production environments, or should I rethink how my data is going to get shared among multiple instances?

**Comment by jacobsa** [comment]
Hi, trying to answer as best I can, point by point.

> Log files from all these instances. Each instance will write to the
> same log files. There are maybe a few logs per second per instance.

gcsfuse doesn't guarantee anything about files that are simultaneously written from multiple hosts. So this will not work (assuming you mean that all instances write to a single file).

> After mounting a bucket and testing it with file and directory creations, I immediately noticed the lag these operations have.

Yes; unfortunately GCS is not particularly low latency. You can run with `--debug_fuse` and maybe `--debug_gcs` to get an idea of what kernel operations are mapping to what GCS operations and how long they take. In general don't expect gcsfuse to be low-latency. It can be high-throughput though, with the appropriate sort of access pattern (parallelizing across files, not flushing frequently, large serial reads, etc).

> Not to mention, issue #204 is a bit disconcerting; (2) can I expect intermittent disconnections while my customers are trying to access the site?

Nobody has given any information in that issue that is useful for root causing or debugging, so at this point I see no reason to be convinced that it's even caused by gcsfuse. But of course you want to thoroughly test your application before launching. If you see the issue, I'd be very happy if you could post something useful to that thread.

> The README also states that when downloading objects they are temporarily stored on the filesystem. (3) Given that one bucket will be at least 140GB, does that mean, to be absolutely safe, that each instance should be at least as large? My instances are configured to run a single codebase, and do not need to be larger than 10GB each. Anything more will really drive the costs up.

This applies only to objects that are modified. Your temporary directories need to be large enough to cover the files that are simultaneously dirty on the local host.

> I read https://cloud.google.com/compute/docs/disks/. It states that "[t]he Regional Storage class has performance that is comparable to persistent disks but with higher latency and less consistent throughput characteristics." I suppose that mostly answers the question about lag, but (1a) does that still apply when mounted, and will the amount of files and directories I mentioned be a problem, as well as the read and write operations that will be performed?

It's hard to answer this in the abstract. Please test it out and report any performance that you find unreasonable.

> I also read that when mounted, each instance "can write data to a file and overwrite critical data from other instances that are also writing data to the storage object simultaneously." Just a few sentences prior, though, it states that "you can read and write data to a bucket from multiple instances simultaneously." That lead me to believe there's no concern about multiple instances accidentally overwriting each other's information. (3) Which is it?

That first quote is in the persistent disk documentation, correct? That product isn't related to gcsfuse.

> I realize the README states this is beta status, but given the lack of alternatives, (4) is the goal of this tool to eventually become the best way of sharing data among instances, or are there alternatives yet unknown that will be announced?

This is a tool for using GCS like a file system. Alternatives include using the official GCS API, which is always going to be no worse in performance (and potentially better), since gcsfuse is also just using the GCS API.
