### ISSUE TITLE
Closing the CLI window breaks the mounting

### ISSUE THREAD

**Issue by gokhandilek** [GoogleCloudPlatform/gcsfuse#239]
I ran the command like gcsfuse mybucket /mnt/gcs-bucket in my crontab like this:
@reboot gcsfuse mybucket /mnt/gcs-bucket
If I close CLI window of  the compune engine VM, I have I/O errors.

Would you know how I can keep this in the background instead of the CLI session?
Thank you.

**Comment by gokhandilek** [comment]
I used this here:
@reboot gcsfuse mybucket /mnt/gcs-bucket
I used crontab because the bucket was not starting.

So If I run gcsfuse mybucket /mnt/gcs-bucket it should  damemonize?

**Comment by jacobsa** [comment]
Yes.

**Comment by gokhandilek** [comment]
Just tried mounting and this is what I am getting:
Using mount point: /mnt/gcs-bucket
Opening GCS connection...
Opening bucket...
Mounting file system...
daemonize.Run: readFromProcess: sub-process: mountWithArgs: mountWithConn: Mount: mount: running fusermount: exit s
tatus 1
stderr:
fusermount: mountpoint is not empty
fusermount: if you are sure this is safe, use the 'nonempty' mount option

**Comment by gokhandilek** [comment]
I have another application which is relying on this bucket. 
How can I get it to run as under a specific user?

**Comment by gokhandilek** [comment]
I have two folders in my bucket. 
I do not get to see the full contents of my bucket from compute engine.
Could you please let me know why I cannot see both of the folders?

**Comment by gokhandilek** [comment]
What happens if you mount and empty mounting point?
Do they just merge from the local storage to my bucket?

**Comment by jacobsa** [comment]
That's a lot of questions (please file separate issues in the future, but):

* It looks like your problem is that the destination directory onto which you want to mount is non-empty. Please make sure it's empty.
* You run gcsfuse under a specific user the same way you would run any binary under a specific user. Log in as that user, schedule in that user's crontab (though I don't know why you would run gcsfuse this way), or use `su`.
* If you're not seeing contents of the bucket, it's likely the issue described in the documentation [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories).
