### ISSUE TITLE
New files created on gcsfuse have null md5sum

### ISSUE THREAD

**Issue by dietervdw-spotify** [GoogleCloudPlatform/gcsfuse#265]
We see about 12% of the files created on a gcsfuse mount do not have the `md5sum` property filled in.

What's the expectation here. Should gcsfuse always calculate and provide this?
Or should we not rely on this?

GCSFuse version: 0.23.0

**Comment by jacobsa** [comment]
Sorry, could you please give more detail about how to reproduce this? How are you writing the files? How are you looking for that property? Is there any common factor for the files?

**Comment by dietervdw-spotify** [comment]
@jacobsa Thanks for looking into this!

The setup we have writes both small text files and and big binary files to a gcsfuse mount.
A small sampling from our logs showed about 12% of the files had a NULL `md5sum` property .

We are reading the files from the GCS bucket using the `google-cloud-storage-1.12.0.jar` java library using the object `com.google.cloud.storage.Storage`:
`storage.get(blobId).getMd5()`

The problem seems to appear only on the big binary files.

Very much open to ideas on how to diagnose this!
Is calculating the md5sum property of new files the responsibility of the gcsfuse drivers, or of the cloud storage?

We need to prioritise some other work first, but will try to spend some time on reproducing this ASAP!
I'll update whenever I have more information to work with!

**Comment by jacobsa** [comment]
This is probably because we make an [optimization](https://github.com/GoogleCloudPlatform/gcsfuse/blob/284558bd039f4859a5fd4b465639fe69725e34a0/internal/fs/fs.go#L91-L107) for writing files that have only been appended to: instead of rewriting their entire contents, we write the new contents into a separate object and then create a composite object in GCS concatenating the two. (The threshold for this is currently [2 MiB](https://github.com/GoogleCloudPlatform/gcsfuse/blob/4abce35dd15ea07f0903c662d3ebf9f531c05cd4/mount.go#L111)).

As documented [here](https://cloud.google.com/storage/docs/hashes-etags#_MD5), the MD5 attribute is generated by GCS only for non-composite objects.
