### ISSUE TITLE
Slow read of large blobs compared to `gcloud storage`

### ISSUE THREAD

**Issue by carlthome** [GoogleCloudPlatform/gcsfuse#2726]
I have a ~5 GB blob that I'm consuming in Python code. The Google Compute Engine VM is in the same region as the Google Storage bucket.

When using `gcloud storage cp gs://my-bucket/my-blob` it takes less than a minute to download to the VM.

When using `python -c "with open("/gcs/my-bucket/my-blob", 'b') as f: f.read()"` it takes several minutes to download the blob into the running process.

I assume (but haven't tried) whether `cp /gcs/my-bucket/my-blob ~` would be faster but I assume it's also slower than `gcloud storage`.

Why is this and can we expect the same excellent high-download speeds that `gcloud storage` offers, from simple reads to /gcs in a future release for GCSFuse? The convenience of "just read like a regular file system" is very appreciated and we don't want to introduce additional bucket storage clients if we can avoid it.

**Comment by kislaykishore** [comment]
@carlthome I think your Python test script could be written a bit more optimally. Instead of downloading the entire 5Gi into memory when you invoke `f.read()`, you could download the content in chunks:
```
with open('<file_path>', 'rb') as f:
    while True:
        buffer = f.read(1024 * 1024)
        if not buffer :
            break
```
`cp <file_path> <dest_path>` should also not take much time.

You can also try a few of the perf-optimizations mentioned [here](https://cloud.google.com/storage/docs/cloud-storage-fuse/performance). Optimizations such as the following could be useful:
* [increase read-ahead size](https://cloud.google.com/storage/docs/cloud-storage-fuse/performance#increase-read-ahead-size)
* [file-cache with/without parallel downloads](https://cloud.google.com/storage/docs/cloud-storage-fuse/performance#improve-throughput)

Lemme know how it goes.

**Comment by raj-prince** [comment]
@carlthome Just wanted to update on the new feature `Buffered Read` in [GCSFuse v3.3.0](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v3.3.0), which accelerates large-file sequential reads (including workloads like simple file copies) (up to 2-5x).

More details about buffered-read, enablement, and cpu/memory resource usage are [here](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v3.3.0).

This feature's performance can be further improved using it with: 
- [1MB kernel read-ahead](https://cloud.google.com/storage/docs/cloud-storage-fuse/performance#increase-read-ahead-size).
- O_DIRECT for application performing large I/O operations (>= 1MB). We have plan to support O_DIRECT via GCSFuse in future release.

Please let us know if you need any help in trying it out, and we would appreciate your feedback.
