### ISSUE TITLE
Mount Bucket on the Kubernetes pod

### ISSUE THREAD

**Issue by andreyvelich** [GoogleCloudPlatform/gcsfuse#328]
I want to mount my Bucket on the Kubernetes container using gcsfuse. 
I followed this example https://github.com/maciekrb/gcs-fuse-sample and it works fine, but I have a question.
Is it possible to mount my bucket on the Kubernetes container without running my container in `privileged` mode ?

Probably, mount it, when I am building my Docker image.

**Comment by wuservices** [comment]
https://github.com/moby/moby/issues/9448#issuecomment-65529399 shows with Docker you can get away with `--device /dev/fuse --cap-add SYS_ADMIN ` instead of `--privileged`. However, there seems to be no equivalent of `--device` for right now for Kubernetes, as people are looking for a feature to do just that to use with `/dev/fuse` in https://github.com/kubernetes/kubernetes/issues/5607#issuecomment-414663936.

**Comment by pre** [comment]
Here’s how to mount a FUSE volume /dev/fuse in Kubernetes without `privileged: true`: https://github.com/kubernetes/kubernetes/issues/7890#issuecomment-766088805

**Comment by avidullu** [comment]
Thanks @pre for the pointer to the k8s issue. From that bug I also found [this link](https://github.com/samos123/gke-gcs-fuse-unprivileged) which has detailed instructions from your post including some minor fixes.
This issue does not seem related to gcsfuse per se so will close this out from here.
Please open a new bug/reopen this if we can provide any further assistance.
Appreciate your help in providing such useful resources to the members of the community!
