### ISSUE TITLE
Uploading bert-master, SQUAD 2.0, and BERT_Large_Cased as a folder does not show up in mounted directory.

### ISSUE THREAD

**Issue by JeevaTM** [GoogleCloudPlatform/gcsfuse#334]
It is as the title says. Nothing shows up but if I create an empty directory and upload files there, it is viewable, writable.

**Comment by aclake16** [comment]
Having this issue as well

**Comment by avidullu** [comment]
Please also share the command like flags you passed to gcsfuse and the names of the buckets used.
I found some bert buckets from [this](https://github.com/google-research/bert#fine-tuning-with-cloud-tpus) link named "gs://bert_models/2018_10_18/" but it has permission denied to view as highlighted by the cloud console link
![bert-permission-denied](https://user-images.githubusercontent.com/1674877/163332564-42e07d91-ce98-49f1-b4f3-03ac3e2dfe6e.png)


Then there is another bucket named "gs://cloud-tpu-checkpoints/bert/" which is readily visible in  cloud console as shown in the below screenshot
![tpu-checkpoint-bert](https://user-images.githubusercontent.com/1674877/163332793-f28502ee-4f1c-42b9-9a3a-dcfd7f054508.png)

And when mounted this bucket using gcsfuse with --implicit-dirs we can clearly see the bert folder as highlighted by this screen
<img width="1791" alt="bert-loading" src="https://user-images.githubusercontent.com/1674877/163333264-7023bfa4-1ac5-4bfa-965c-75afdd3a2a6c.png">

So I'll close this bug out since we cannot repro this. Please feel free to file a fresh issue/reopen with more details around the name of the bucket and flags and we will be happy to assist you.
