### ISSUE TITLE
Support --no-mtime

### ISSUE THREAD

**Issue by MaT1g3R** [GoogleCloudPlatform/gcsfuse#339]
We'd like to mount something that does not allow updates. When we try to `cp` a file into the mount we get this result in debug mode:
```
fuse: 2019/07/10 21:13:27.787402 *fuseops.SetInodeAttributesOp error: SetMtime: UpdateObject: googleapi: Error 403: my-app@my-proj.iam.gserviceaccount.com does not have storage.objects.updateaccess to bucket/foo.txt., forbidden
```
We looked at  #133 and it seems like it doesn't help us.

Thanks

**Comment by avidullu** [comment]
The error you have mentioned seems to indicate permission issues. Not updating mtime might cause issues with the metadata of the object. Please let us know if you see this issue with a bucket where you have all the permissions.
Closing this out for now since it's ~3 years old. Please feel free to reopen with latest logs so we can support you better.
