### ISSUE TITLE
On write, do GCS errors trigger file write errors immediately?

### ISSUE THREAD

**Issue by AntonyKing7D** [GoogleCloudPlatform/gcsfuse#502]
From the docs, I see that GCSfuse uses a staging area for writes. When the file is closed, would a subsequent error in GCS cause the write to return an error ? Or does the writing process get a 'success' immediately that the staging file is written ?

**Comment by gaul** [comment]
The error cannot be triggered immediately and can be shifted in time.  The most obvious way to trigger this is a network disconnection.  The order of operations looks like:

* client writes data, gcsfuse stages write locally, write return success
* client closes file, gcsfuse issues requests to GCS
* if this succeeds, the close will return 0, otherwise it will return -1 and set `errno`

Note that some incorrectly-written applications do not check the close result since it is unclear how to handle it.  Some background:

https://stackoverflow.com/questions/33114152/what-to-do-if-a-posix-close-call-fails

**Comment by AntonyKing7D** [comment]
Thanks for clarifying that - so I need to go check the application (proftpd in this case) to see if it is well behaved.
