### ISSUE TITLE
Does GCSFuse v0.33.2 support 50 GB File Upload/Download size limit?

### ISSUE THREAD

**Issue by jxb696** [GoogleCloudPlatform/gcsfuse#504]
Team, We are looking for a documentation/direction to see if GCSFuse v0.33.2 supports 50GB file upload/download of files from GCS Buckets. 
Thanks.

**Comment by gaul** [comment]
I recommend testing with 0.34 which has a memory consumption fix:

https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.34.0

**Comment by jxb696** [comment]
Thank you @gaul . looks like the memory utilized for uploading a 10 GB file released with v0.34 but I'm still receiving this error - "Software caused connection abort" and "cannot open directory - Transport endpoint is not connected"

**Comment by jxb696** [comment]
@gaul  - I used following 2 scenarios for a single 10 GB file -

1. DD command - it's creates a 10 GB file and releasing the memory; but upload to destination bucket is not working, I can see "0 Byte file in bucket" ; Bucket is going into in-operable state (Software caused connection abort and cannot list directory, Transport endpoint is not connected)
2. CP command - Created a 10GB file on EBS, Copied a file to destination filesystem bucket mount and GCSFuse uploaded the file to destination bucket but not releasing the memory.. (This scenario was encountered with v0.32) The GCSFuse process is still on TOP command.

**Comment by gaul** [comment]
@lezh 44263afe9eabae403569ddc0e4893f3943a294d2 reverted the gcloud sync and thus the OOM fix in 3e7d1f4673d3ff411292abee4ef907e0cfea05a0.  Was there some issue with versioning that accidentally caused this?

@jxb696 Could you try compiling your own gcsfuse cherry-picking 3e7d1f4673d3ff411292abee4ef907e0cfea05a0?

**Comment by lezh** [comment]
@gaul  I see. That's because https://github.com/GoogleCloudPlatform/gcsfuse/commit/3e7d1f4673d3ff411292abee4ef907e0cfea05a0 did not update the library version in [go.mod](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/go.mod). Then, https://github.com/GoogleCloudPlatform/gcsfuse/commit/44263afe9eabae403569ddc0e4893f3943a294d2 tried to sync all the libraries, which reverted gcloud back to the version recorded in the [go.mod](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/go.mod).

**Comment by lezh** [comment]
Please verify if this is fixed in [v0.34.1](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.34.1)

**Comment by jxb696** [comment]
@lezh  - v0.34.1 fixed memory issues uploading large files.
