### ISSUE TITLE
fuseops.SyncFileOp error: input/output error

### ISSUE THREAD

**Issue by ddbasciano** [GoogleCloudPlatform/gcsfuse#516]
Hello All,
Whit new version of gcsfuse (0.34.1) I'm facing these errors:
> {"name":"root","levelname":"ERROR","severity":"ERROR","message":"fuse: *fuseops.SyncFileOp error: input/output error\n","timestampSeconds":1618078232,"timestampNanos":397649044}
> {"name":"root","levelname":"ERROR","severity":"ERROR","message":"fuse: *fuseops.FlushFileOp error: input/output error\n","timestampSeconds":1618078532,"timestampNanos":501263187}

The error seems to affect only large files, in my case 200GB

The job is running with following flags:
> bh5adm    9219     1  0 Apr09 ?        00:32:21 /usr/bin/gcsfuse --foreground --log-file /var/log/fusermount.log --debug_gcs --key-file /etc/google/auth/application_owner_credentials.json --temp-dir /hana/data/backup/tmp_gcsfuse ifrs17-non-prod-backup-bucket /hanabackup

I already saw this related issue (#407), but in my case the last version of gcsfuse give same error

Do you have any idea to how solve it?

Thank you,
BR
Davide

**Comment by avidullu** [comment]
Can you retry with the latest version of gcsfuse for the same file (200 GB as you mentioned) and let us know the log messages you see including info/warning/errors so that we can have a holistic view of the operations.

Also can you explain in what operation on the file do you get the errors? Is it just listing or reading/writing?

**Comment by avidullu** [comment]
Closing out due to inactivity.
