### ISSUE TITLE
multiple arguments for -bucket and -mount_point

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#55]
Would it be possible to have an option for gcsfuse to specify multiple arguments for -bucket and  -mount_point parameters?

e.g. gcsfuse -bucket=b1,b2 -mount_point=/data1,/data2 

this would be very useful because then we could have a single gcsfuse process instead of multiplying gcsfuse processes as we add more buckets and mount_points.

Alternative solution could be to have an option to mount new buckets without stopping gcsfuse process so that buckets mounted earlier work without interruptions. 

e.g.  
gcsfuse -bucket=b1 -mount_point=/data1
gcsfuse -bucket=b2 -mount_point=/data2 -append on

**Comment by jacobsa** [comment]
The intent is to have one gcsfuse process per file system, which keeps everything simpler. You imply that having multiple gcsfuse processes is a problem, but why is that?

**Comment by trollius** [comment]
Hi Aaron!

For instance, it would be easier to monitor one process on servers with running gcsfuse for different number of buckets than to follow multiple processes.  Maybe it would be possible to add an option to gcsfuse so that a user could choose how to run gcsfuse: either as one process per bucket or one process per multiple buckets modes?

**Comment by jacobsa** [comment]
Adding an option fails on the "keep everything simpler" part. :-) Can you explain the difficulty with monitoring multiple processes? What about if you run your own program that forks and execs the gcsfuse processes you need, with shared stderr if preferred, and then you monitor that process or process group?

**Comment by trollius** [comment]
1) for instance, if we have 5 buckets mounted to 1st server, 2 buckets mounted to the second one and 10 mounted to the third, then in zabbix we can't make a universal template for monitoring gcsfuse processes, because we will have different number of gcsfuse processes on each server. So we will need to do an independent check for each case. Moreover, as buckets can be mounted to servers automatically, thus changing the number of gcsfuse processes, zabbix template will be outdated quite quickly.
2) well, it requires quite some knowledge to write a script which will be doing "fork" and launch of several gcsfuse processes...

**Comment by jacobsa** [comment]
Here are the problems I see with this:

*   Aside from the configuration difficulty, monitoring multiple processes seems like it would be _better_ than monitoring a single one, because if one dies you can tell which one it was.

*   More importantly, if one dies it doesn't take down all of the others--with a monolithic process you have shared fate between all of the file systems, which is risky.

*   Doing this makes the program more complex, which is unfortunate. But it also invites even more complexity: once you support multiple buckets in a single process, someone is going to want to have different permissions bits for each. And then someone else is going to want to have different owning users for each. This increases the surface for bugs, and makes it much harder to test.

Given all of this, and since you can build the monolithic multiple-bucket program by calling the single-bucket program multiple times, I don't think I'd like to do this.

If you need help building the program that calls gcsfuse multiple times, let me know and I'll leave the issue open and try to write some sample code at some point that you can use as a starting point.

**Comment by trollius** [comment]
Thanks a lot for your detailed explanation! We agree that it's better to manage separately - we will test some approaches and share the code so others can use it as well. So let's close the ticket for now - and once there are updates we will comment on it to reopen

**Comment by jacobsa** [comment]
Sounds good, thanks!
