### ISSUE TITLE
Google Cloud FUSE with Cloud Run [Errno 5] Input/output error: '/database' but already granted Storage Object Admin access

### ISSUE THREAD

**Issue by juliantcchu** [GoogleCloudPlatform/gcsfuse#576]
I am using GCP's Cloud FUSE together with Cloud Run, as outlined in this tutorial by google (https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse#cloudrun_fs_code-python). However, after I deployed the app, the app is not able to access that folder but instead got this error in the log `[Errno 5] Input/output error: '/database'` , where 'database' is the folder name From what I read online, this is usually due to not having sufficient permission. However, I checked the dashboard at Cloud FUSE and I have already granted Storage Object Admin access to the service account of the app.

The app is written in python 3.9. I am not able to perform` os.listdir('/database')`, and `os.path.isdir('/database')` returns `false`. However, when I used `os.listdir('/')`, 'database' is one of the items on the list.

**Comment by lezh** [comment]
> usually due to not having sufficient permission

Recent changes have correct these errors to "permission denied" instead of "input/output error". The "input/output error" is somewhat an "unknown" error in this case. Can you add "--debug_gcs" flag to the command that mounts gcsfuse to get some internal logs?

Once you have the gcs logs, you can check the requests right before the failure. That might tell you the real issue.

**Comment by avidullu** [comment]
As mentioned, please provide us some logs so we can comprehend the issue better.

**Comment by avidullu** [comment]
Closing out due to inactivity.
