### ISSUE TITLE
Failed to unmount in response to SIGINT

### ISSUE THREAD

**Issue by trollius** [GoogleCloudPlatform/gcsfuse#78]
Hi Aaron,

When our server has little memory left (RAM), only about 180M (405M is occupied out of 589M), gcsfuse can't shutdown its work correctly. After we press ctrl+c, gcsfuse returns:
^C2015/06/16 18:07:18.007276 Received SIGINT, attempting to unmount...
2015/06/16 18:07:18.007495 Failed to unmount in response to SIGINT: fork/exec /usr/bin/fusermount: cannot allocate memory
At this moment, gcsfuse uses 178M of RAM.
So, we can use two ways:
1) free some RAM (for example: we can stop mysqld process or other running processes), that gcsfuse will can gracefully exit.
2) we can wait some time, that gcsfuse himself free some RAM from what it uses (garbage collection).

Maybe, you can tell us a third way? For example: can gcsfuse free RAM more frequently than it does now?
Or this issue is connected with fuse?

**Comment by jacobsa** [comment]
Background question for my curiosity: I've never seen this happen because I've never run into a situation where memory can't be allocated from the OS. I guess you have swapping disabled?

I'm not sure what to say here. In order to fork and execute the fusermount binary, some memory will be needed. However you've set up limits on RAM usage (and disabling swap, etc.), you'll need to change the limits so there is more memory available. Alternatively you can run `fusermount -u /path/to/mount/point` yourself directly.
