### ISSUE TITLE
chmod / chown Function not implemented

### ISSUE THREAD

**Issue by nmathon** [GoogleCloudPlatform/gcsfuse#80]
Hi !
I use a java program on a gcsfuse bucket and it failed due to a "Function not implemented" on the chmod command. I can't modify the program. What can I do ?
Thanks

**Comment by jacobsa** [comment]
See [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/18767951ea35769e7740a9c741b31884e8098e41/docs/semantics.md#permissions-and-ownership) for documentation about permissions and ownerships.

gcsfuse doesn't support changing permissions because there is no sense in which posix permissions for the local machine mean anything in GCS. Perhaps the application is calling chmod because it wants a certain mode for a file though, in which case maybe you can use `--file-mode` or `--dir-mode` to make that happen.
