### ISSUE TITLE
Mounting bucket via fstab hangs

### ISSUE THREAD

**Issue by nazikus** [GoogleCloudPlatform/gcsfuse#862]
**Describe the bug**
Mounting bucket via fstab hangs

**To Collect more Debug logs**
```
$ cat /etc/fstab
...
service-dataset-bucket-v2  /mnt/dataset      gcsfuse ro,allow_other,noauto

$ mount /mnt/dataset
Calling gcsfuse with arguments: -o ro -o allow_other service-dataset-bucket-v2 /mnt/dataset
2022/12/01 14:10:16.381445 Start gcsfuse/0.41.9 (Go version go1.18.4) for app "" using mount point: /mnt/dataset
2022/12/01 14:10:16.388247 Opening GCS connection...
# hangs forever
```
Several gcsfuse processes hanging:
```bash
pgrep -a gcsfuse

45643 /sbin/mount.gcsfuse service-dataset-bucket-v2 /mnt/dataset -o ro,allow_other
45648 gcsfuse -o ro -o allow_other service-dataset-bucket-v2 /mnt/dataset
45660 /usr/bin/gcsfuse --foreground -o ro -o allow_other service-dataset-bucket-v2 /mnt/dataset
```

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Platform: native
 - Version: 0.41.9 (Go version go1.18.4)

**Additional context**
If I run arguments from logs above ("Calling gcsfuse with arguments") from user space, it mounts ok:
```bash
gcsfuse -o ro -o allow_other service-dataset-bucket-v2 /mnt/datas
```

**Comment by raj-prince** [comment]
Hi @nazikus,

I tried to simulate the mounting process you mentioned above and able to mount it successfully using the **"mount mount_point"** command. There might be chance, the issue in your case is coming due to command invocation by the different user (root vs non-root one) invocation, but not sure.

Can you please enable the gcsfuse-logs and share it, so that we will have more context about the issue?

To enable the logs, you need to replace the arguments **"ro,allow_other_noauto"** with  **"ro,allow_other,noauto,debug_fuse=1,debug_fs=1,debug_gcs=1,debug_http=1,log_file=<log_file_path>,log_format=text"** in the /etc/fstab file.

This will write all the logs in the file. You need to replace the <log_file_path> with any absolute path.

Thanks,
-Prince

**Comment by sethiay** [comment]
Closing the issue since we haven't heard back from the customer.
