### ISSUE TITLE
EEXIST can be returned for a new file creation request

### ISSUE THREAD

**Issue by ikholopov-omni** [GoogleCloudPlatform/gcsfuse#927]
**Describe the bug**
We noticed that in extremely rare occasions the following Python code
```
open('path/in/gcsfuse/mount', 'a')
```
fails with FileExistError,  which [translates](https://docs.python.org/3/library/exceptions.html#FileExistsError) to EEXIST returned in open request.

I believe the following is taking place:
1) The LookUpInode op translates to get GCS request out to check if file exists - it does not
2) The CreateFile op translates to GCS create request with preconditon that file should be new (as it always does for this op). The request is dispatched, reaches GCS backend and file is created, but the response doesn't reach the client. The request is retried, and fails with precondition failure as file already exists.

The problem is that the request to create a file with preconditon that it shouldn't exist yet is not idempotent by definition, yet it can be retried and will result in EEXIST error returned. I've checked and CPython doesn't do anything special, it uses open syscall, which according to [man](https://man7.org/linux/man-pages/man2/open.2.html) should return EEXIST *only* if both O_CREAT and O_EXCL are specified. Which makes me conclude that this behavior is a bug in gcsfuse.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Platform Kubernetes (GKE)
 - Version 0.37, reproduced in newer versions

**Comment by raj-prince** [comment]
Thanks @ikholopov-omni, for letting us know this behavior and providing such comprehensive explanation!

According to me, the right fix for this scenario would be to catch this precondition-fail error (or log some warning) and don't pass it to kernel.  We have made a similar [fix](https://github.com/GoogleCloudPlatform/gcsfuse/pull/910) in [go-storage-client](https://pkg.go.dev/cloud.google.com/go/storage) workflow, which is used when we pass  "--experimental-enable-storage-client-library" while mounting with gcsfuse. As the flag suggest, right now this is in experimental phase but soon (end this month, or early next month) we will enable this flag by default. Most probably this will fix this issue. 

Most probably, by looking at the used gcsfuse version (0.37), this issue would be in [jacobsa/gcloud](https://pkg.go.dev/github.com/jacobsa/gcloud) client. Since, we have almost moved on the go-storage-client, team has decided to not invest much on the current jacobsa/gcloud client.

Please let us know if you face similar issue with go-storage-client.

Thanks,
Prince.

**Comment by sethiay** [comment]
We investigated this further and found that this behaviour is expected. i.e. if the request to create file is successful at GCS side and response doesn't reach back to client, then retry will happen and that will fail with precondition error. 
The request to create new object(file) with the precondition that it shouldn't exist is an idempotent request (See [this](https://cloud.google.com/storage/docs/retry-strategy#idempotency-operations) and [this](https://github.com/GoogleCloudPlatform/gcsfuse/blob/4859983c583c9f09f3edd26651c8de7f4e490439/vendor/cloud.google.com/go/storage/writer.go#L177)). 
Also, these failures are rare to happen and if they happen, errors are expected. 

Closing this issue. Please re-open if you face any other issues.

**Comment by ikholopov-omni** [comment]
I am afraid I can't agree with the conclusion of this analysis. While it is correct that the request for the file creation in GCS API the `ifGenerationMatch` is required for the idempotency, the user doesn't interact with GCS API in FUSE, but with kernel API. And it would be exactly the job of the FUSE implementation to translate idempotent original call (open with attach mode, no exclusivity, no requirement to create new) to the idempotent call to GCS API (insert or leave as-is if exists).

Anyway, I believe that https://github.com/GoogleCloudPlatform/gcsfuse/pull/910/files should address the problem, so I'll reopen this bug only if we observe this issue again in a new client.

Thanks!
